# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'plan date')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('recipe', models.TextField(blank=True, null=True)),
                ('speed', models.IntegerField(choices=[(1, b'one star'), (2, b'two stars'), (3, b'three stars')], default=1, null=True)),
                ('complexity', models.IntegerField(choices=[(1, b'one star'), (2, b'two stars'), (3, b'three stars')], default=1, null=True)),
                ('results', models.IntegerField(choices=[(1, b'one star'), (2, b'two stars'), (3, b'three stars')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('eaten', models.BooleanField(default=False)),
                ('meal_type', models.CharField(choices=[(b'breakfast', b'breakfast'), (b'lunch', b'lunch'), (b'dinner', b'dinner'), (b'dessert', b'dessert'), (b'snack', b'snack'), (b'tapas', b'tapas')], max_length=40, null=True)),
                ('dayplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.DayPlan')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('dishes', models.ManyToManyField(to='themenu.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='tags',
            field=models.ManyToManyField(to='themenu.Tag'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tags',
            field=models.ManyToManyField(to='themenu.Tag'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='themenu.Ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(to='themenu.Tag'),
        ),
    ]
