# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0002_auto_20161211_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tags',
            field=models.ManyToManyField(blank=True, to='themenu.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set([('date', 'meal_type')]),
        ),
    ]
