# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import themenu.models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0003_auto_20161212_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.TextField(default=themenu.models.randcolor),
        ),
    ]
