# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0004_auto_20161210_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='completed',
            new_name='prepared',
        ),
    ]
