# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0004_auto_20170105_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=b'list date')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.BooleanField(default=False)),
                ('grocerylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.GroceryList')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='themenu.GroceryListItem', to='themenu.Ingredient'),
        ),
    ]
