# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0005_auto_20161210_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dayplan',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2016, 12, 10), verbose_name=b'meal date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='themenu.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='themenu.Tag'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='themenu.Tag'),
        ),
        migrations.DeleteModel(
            name='DayPlan',
        ),
    ]
