# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0005_auto_20170105_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='grocerylistitem',
            name='grocerylist',
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='themenu.Meal'),
        ),
        migrations.DeleteModel(
            name='GroceryList',
        ),
    ]
