# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0006_auto_20170107_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylistitem',
            name='meal',
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='themenu.Course'),
        ),
    ]
