# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import themenu.models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0007_auto_20170107_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=themenu.models.randcolor, max_length=48),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=48),
        ),
    ]
