# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0009_auto_20170114_2252'),
        ('themenu', '0009_auto_20170122_1113'),
    ]

    operations = [
    ]
