# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='themenu.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='themenu.Team'),
            preserve_default=False,
        ),
    ]
