# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0012_auto_20170125_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='themenu.MyUser'),
            preserve_default=False,
        ),
    ]
