# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0014_auto_20170128_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themenu.Team'),
        ),
    ]
