# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0015_auto_20170128_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ease',
            field=models.IntegerField(choices=[(1, b'complex'), (2, b'moderate'), (3, b'simple')], null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='results',
            field=models.IntegerField(choices=[(1, b'not so good'), (2, b'okay'), (3, b'tasty')], null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='speed',
            field=models.IntegerField(choices=[(1, b'more than 1 hour'), (2, b'30 min - 1 hour'), (3, b'less than 30 min')], null=True),
        ),
    ]
