# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0018_remove_randomgroceryitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ease',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='results',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='speed',
        ),
    ]
