# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0019_auto_20170422_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
