# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0020_auto_20170422_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1000)),
                ('fastness', models.IntegerField(blank=True, choices=[(1, b'over 1 hour'), (2, b'30 min - 1 hour'), (3, b'less than 30 min')], null=True)),
                ('ease', models.IntegerField(blank=True, choices=[(1, b'complicated'), (2, b'moderate'), (3, b'simple')], null=True)),
                ('results', models.IntegerField(blank=True, choices=[(1, b'not so good'), (2, b'okay'), (3, b'tasty')], null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.Dish')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.MyUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dishreview',
            unique_together=set([('myuser', 'dish')]),
        ),
    ]
