# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0021_auto_20170424_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishreview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
