# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0022_auto_20170424_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
