# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0023_auto_20170424_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_prep',
            field=models.CharField(choices=[(b'cook', b'cook'), (b'buy', b'buy'), (b'leftover', b'leftover')], max_length=40, null=True),
        ),
    ]
