# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def replace_dish_ingredients(apps, schema_editor):
    """Dish has Ingredient foreign keys, we now need IngredientAmount

    Add an IngredientAmount with empty amount (already created) for every Ingredient"""
    IngredientAmount = apps.get_model('themenu', 'IngredientAmount')
    Dish = apps.get_model('themenu', 'Dish')
    for dish in Dish.objets.all():
        for ingredient in dish.ingredients.all():
            ia = IngredientAmount(ingredient=ingredient)
            ia.save()
            dish.ingredient_amounts.add(ia)
            dish.save()


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0025_auto_20170628_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('oz ', 'ounce'), ('lb', 'pound'), ('mg', 'milligram'), ('g', 'gram'), ('kg ', 'kilogram'), ('c', 'cup'), ('gill', 'gill'), ('ml ', 'milliliter'), ('L', 'liter'), ('pt ', 'pint'), ('qt', 'quart'), ('gal', 'gallon'), ('tsp ', 'teaspoon'), ('tbsp', 'tablespoon'), ('fl oz', 'fluid ounce'), ('dash', 'dash'), ('pinch', 'pinch'), ('mm', 'millimeter'), ('cm', 'centimeter'), ('m', 'meter'), ('in', 'inch'), ('ft', 'foot'), ('strip', 'strip'), ('stick', 'stick')], max_length=40, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient_amounts',
            field=models.ManyToManyField(blank=True, to='themenu.IngredientAmount'),
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='ingredient_amount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='themenu.IngredientAmount'),
        ),
        # TODO: do i care about actually making the reverse function to restore these?
        migrations.RunPython(replace_dish_ingredients, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='grocerylistitem',
            name='ingredient',
        ),
    ]
