# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0025_auto_20170628_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('oz ', 'ounce'), ('lb', 'pound'), ('mg', 'milligram'), ('g', 'gram'), ('kg ', 'kilogram'), ('c', 'cup'), ('gill', 'gill'), ('ml ', 'milliliter'), ('L', 'liter'), ('pt ', 'pint'), ('qt', 'quart'), ('gal', 'gallon'), ('tsp ', 'teaspoon'), ('tbsp', 'tablespoon'), ('fl oz', 'fluid ounce'), ('dash', 'dash'), ('pinch', 'pinch'), ('mm', 'millimeter'), ('cm', 'centimeter'), ('m', 'meter'), ('in', 'inch'), ('ft', 'foot'), ('strip', 'strip'), ('stick', 'stick')], max_length=40, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.Amount')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themenu.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient_amounts',
            field=models.ManyToManyField(blank=True, to='themenu.IngredientAmount'),
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='ingredient_amount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='themenu.IngredientAmount'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_amounts',
            field=models.ManyToManyField(blank=True, through='themenu.IngredientAmount', to='themenu.Amount'),
        ),
    ]
