# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themenu', '0026_IngredientAmounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='descriptor',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
